### ISSUE TITLE
Implement JSONParse and JSON

### ISSUE THREAD

**Issue by sompylasar** [KnowSheet/KnowSheet-REPL#3]
`JSONParse` should handle asynchronous responses and provide asynchronous result. `JSON` could do this, too.

Examples:
- `JSONParse(HTTP(GET("http://httpbin.org/get?test=1")).body)` – this one is trivial, I can return a promise from JSONParse.
- `JSONParse(HTTP(GET("http://httpbin.org/get?test=1")).body).args` – this one is more complex to implement because half of the expression is asynchronous (I can return a promise from `JSONParse`), another half depends on the result if it (`.args` on the promise will be missing and thus useless until the promise is fulfilled). Likely have to rewrite the expression before evaluation.

**Comment by dkorolev** [comment]
Ah, please! Just return an object from `JSONParse`.

No need to rewrite expressions. If it throws or returns an undefined, so be it.

A minor change that might make sense is to actually print a message along the lines of `"'undefined' was returned."` if the expression has been using `JSONParse()`. And, if it is used in a piping mode, do `process.exit(-1);` or something along those lines.

**Comment by sompylasar** [comment]
@dkorolev I cannot. Half of the expression is asynchronous. It does not block until the data is ready.

**Comment by sompylasar** [comment]
@dkorolev I made a mistake on the "trivial" line. It should be 
`JSONParse(HTTP(GET("http://httpbin.org/get?test=1")).body)`

**Comment by dkorolev** [comment]
Got it. I suggest we postpone this conversation until you have a prototype.
Green light for it! :-)
ᐧ

Thanks,
Dima

http://dimakorolev.com/ | http://www.linkedin.com/in/dimakorolev |
dmitry.korolev@gmail.com | +1 (312) 593 2783

**Comment by sompylasar** [comment]
Please see PR #4 which fixes this issue and adds async evaluation of properties.

```
$ echo 'JSONParse(HTTP(GET("http://httpbin.org/get?test=1")).body).args' | node run
--------------------------------------------------------------------------------
{ test: '1' }
--------------------------------------------------------------------------------
(420ms)
$ echo 'JSONParse(HTTP(GET("http://httpbin.org/get?test=1")).body).args' | node run | cat
{ test: '1' }
```

**Comment by dkorolev** [comment]
I assume this one is done.

**Comment by sompylasar** [comment]
Done.
